nelmio_api_doc:
    documentation:
        info:
            title: Call Center Management System API
            description: API dokumentacja dla systemu zarządzania centrum obsługi klienta
            version: 1.0.0
        security:
            - Bearer: []
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        paths:
            /api/auth/login:
                post:
                    tags:
                        - Authentication
                    summary: Logowanie do systemu
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        email:
                                            type: string
                                        password:
                                            type: string
                                    required:
                                        - email
                                        - password
                    responses:
                        '200':
                            description: Zwraca token JWT
    areas: # to filter documented areas
        path_patterns:
            - ^/api/(?!doc$) # Exclude /api/doc
            - ^/api/users 