nelmio_api_doc:
    documentation:
        info:
            title: Call Center Management System API
            description: API documentation for the call center management system
            version: 1.0.0
        security:
            - Bearer: []
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        paths:
            /api/auth/login:
                post:
                    tags:
                        - Authentication
                    summary: Login to the system
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        email:
                                            type: string
                                        password:
                                            type: string
                                    required:
                                        - email
                                        - password
                    responses:
                        '200':
                            description: Returns JWT token
    areas: # to filter documented areas
        path_patterns:
            - ^/api/(?!doc$) # Exclude /api/doc
            - ^/api/users 