nelmio_api_doc:
    documentation:
        info:
            title: API Documentation
            description: API documentation for the application
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$) # Accepts routes under /api except /api/doc 